[tool.typeo]
verbose = false

[tool.typeo.scripts."export.online".commands.deepclean]
kernel_length = 1
stride_length = 0.001953125
sample_rate = 4096
channels = "channels.deepclean.txt"
streams_per_gpu = 1
instances = 6
max_latency = 0.5
weights = "${WEIGHTS_PATH}"
platform = "onnxruntime_onnx"
repo_dir = "${HOME}/repos/deepclean-online

[tool.typeo.scripts."client.deepclean.online"]
data_dir = "${DATA_DIR}"
write_dir = "${WRITE_PATH}"
kernel_length = 1
stride_length = 0.001953125
sample_rate = 4096
inference_rate = 750
channels = "channels.deepclean.txt"
sequence_id = 1001
url = "localhost:8001"
model_name = "deepclean-stream"
model_version = 1
preprocess_pkl = "ppr.bin"
timeout = 10
stats_file = "${EXPT_NAME}.csv"
log_file = "${EXPT_NAME}.log"
