name: build-containers

on:
  push:
    branches: main

env:
  NGC_TAG: "22.02"
  POETRY_VERSION: "1.2.0a2"
  CONDA_TAG: "4.10.3"

jobs:
  main:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          export:
            - '.github/workflows/build-containers.yaml'
            - 'projects/gw-iaas/export/**'
            - 'libs/hermes/hermes.quiver/**'
            - 'libs/hermes/hermes.typeo/**'
          client:
            - '.github/workflows/build-containers.yaml'
            - 'projects/gw-iaas/clients/**'
            - 'libs/hermes/hermes.stillwater/**'
            - 'libs/hermes/hermes.gwftools/**'
            - 'libs/hermes/hermes.quiver/**'
            - 'libs/hermes/hermes.typeo/**'
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: GW-IaaS export container build
      id: gw-iaas-export-container-build
      uses: docker/build-push-action@v2
      if: steps.filter.outputs.export == 'true'
      with:
        context: .
        file: projects/gw-iaas/export/Dockerfile
        push: true
        tags: fastml/gwiaas.export:latest
        build-args: |
          TAG=${{ env.NGC_TAG }}
          POETRY_VERSION=${{ env.POETRY_VERSION }}
    -
      name: GW-IaaS client container build
      id: gw-iaas-client-container-build
      uses: docker/build-push-action@v2
      if: steps.filter.outputs.client == 'true'
      with:
        context: .
        file: projects/gw-iaas/clients/Dockerfile
        push: true
        tags: fastml/gwiaas.client:latest
        build-args: |
          CONDA_TAG=${{ env.CONDA_TAG }}
          POETRY_VERSION=${{ env.POETRY_VERSION }}
    -
      name: Triton Server pull-push
      id: gw-iaas-server-container-push
      run: |
        docker pull nvcr.io/nvidia/tritonserver:${{ env.NGC_TAG }}-py3
        docker tag nvcr.io/nvidia/tritonserver:${{ env.NGC_TAG }}-py3 fastml/gwiaas.tritonserver:latest
        docker push fastml/gw-iaas-tritonserver:latest
